### ISSUE TITLE
Changing the media library clip selection (instead of deselecting) doesn't work properly

### ISSUE THREAD

**Issue by nekohayo** [pitivi/pitivi#121]
This is a fun/cute one. Let's say you have clips A B C D in the media library.

1. Select B + C, insertEnd. Result: 2 clips inserted in the timeline.
2. Click on B to select B only, insertEnd: B+C get inserted!

If you click on D or an empty space to deselect B+C before clicking on B at step 2, the behavior is correct (only one clip will be inserted).

Would be nice to cover this with a small dogtail test while we're at it.

**Comment by aleb** [comment]
https://phabricator.freedesktop.org/T7478
