### ISSUE TITLE
Thumbnails on timeline clips sometimes don't ever show up

### ISSUE THREAD

**Issue by nekohayo** [pitivi/pitivi#130]
I have not been able to pinpoint exactly how to trigger this, but "odinho's project" exhibits this issue when you load it: the 2nd clip on the timeline generates and displays its thumbnails, but the 1st clip right before it never displays any thumbnails, no matter the zoom level.

I've seen other cases where this happens, such as a test project I had here that has 5-6 clips one after another on the timeline: half of them don't show thumbnails.

**Comment by aleb** [comment]
https://phabricator.freedesktop.org/T3168
