### ISSUE TITLE
Pipeline flushes change the position

### ISSUE THREAD

**Issue by nekohayo** [pitivi/pitivi#133]
Now that issue #3 is merged to master, this reveals a longstanding bug: let's say you have clip A and B one after another on the timeline. Seek somewhere in the middle of clip A, then slide clip B somewhere else.

Result: the image shown in the viewer changes, as if something in our pipeline was seeking forward everytime.

Another detail you may notice is that those "seeks" occur only on a forward basis... if you drag clip B to the left or to the right, the seeks always go "forward" in clip A no matter the direction of the drag.

**Comment by aleb** [comment]
https://phabricator.freedesktop.org/T7477
