### ISSUE TITLE
[BUG]Preview area error!

### ISSUE THREAD

**Issue by MuSamDu** [pitivi/pitivi#140]
When i start a new project and import files and everything goes ok, but when i open the project again, the video preview area (the framed area to play&preview the edited video when editing)doesn't work! Also, the timeline arrow (that red one which points the time on the timeline when i preplay the video) doesn't work either! So i started it in the terminal and found this error:
***
    ERROR 17:56:59 pipeline            
     _asyncDoneNotReceivedCb: we didn't get async done, this is a bug (usr/lib/pitivi/python/pitivi/utils/pipeline.py:402)
    ERROR 17:56:59 pipeline            
     _recover: Pipeline error detected during playback, resetting -- num tries: 1 (usr/lib/pitivi/python/pitivi/utils/pipeline.py:527)
***
Also, i'm using the portable version on fedora (that tared alternative version)   
Who can help???

**Comment by nekohayo** [comment]
Hi, you should come on the IRC channel to ask for help debugging that issue, sounds really strange.

P.s.: github is not our official bug tracker, and this is not the official pitivi git repository either, take a look at http://wiki.pitivi.org/wiki/Bug_reporting
