### ISSUE TITLE
Window invisible and not usable after starting from source directory

### ISSUE THREAD

**Issue by FunkyM** [pitivi/pitivi#141]
I was tempted to try HEAD but can't get it to run properly.
I don't want to use nor install flatpak, just using the usual system based autotools install.
However on my system I do not see the main application GUI at all.
The activities overview shows a black window that if switched apparently takes all input but is not visible (transparent).

I am running pitivi from the source directory like this:
`$ PITIVI_DEVELOPMENT=1 ./bin/pitivi`

Versions:
* openSUSE Tumbleweed
* GNOME 3.20.x
* GTK 3.20.6
* gstreamer 1.8.1, GES 1.8.1, gst-transcoder HEAD master, gst-plugins-bad 1.8.1
* cairo 1.25.2
* NVIDIA binary drivers

I'd appreciate a hint on how to debug this properly. Thanks.

**Comment by aleb** [comment]
You could try also specifying PITIVI_DEBUG=4 (or 5, 6) to get some more info.

No idea what could cause the empty window.. 

See here how to set up the dev env to be able to run HEAD: https://github.com/pitivi/pitivi/blob/master/docs/HACKING.md#setup-pitivi
(also needs flatpak..) If you can reproduce the empty window with the dev env set up like that please file a bug on https://phabricator.freedesktop.org/maniphest/task/create/?projects=pitivi

I'll close the task. Please ask us in #pitivi on freenode if you want to use a different environment.

**Comment by aleb** [comment]
BTW, sorry we still keep here the old issues, we should close them and maybe move them to phabricator.

**Comment by FunkyM** [comment]
For reference: This was a problem with gst-validate making it attempt to load plugins from the wrong directory. This is fixed with gst-validate version 1.8.3.
