### ISSUE TITLE
gst-core-error-quark ?

### ISSUE THREAD

**Issue by procod3R** [pitivi/pitivi#142]
![screenshot from 2016-10-08 15-44-35](https://cloud.githubusercontent.com/assets/5165343/19213505/49ce08b0-8d6e-11e6-916b-62ac87aa3315.png)

**Comment by aleb** [comment]
What are the steps to reproduce the problem?

**Comment by procod3R** [comment]
Add effect
"Agingtv"

**Comment by aleb** [comment]
Works fine here, please provide step by step instructions. What Pitivi version are you using?

**Comment by aleb** [comment]
This might be as a result of a drag&drop operation. What window manager are you using?

**Comment by procod3R** [comment]
v0.95  on Linux Mint 18

**Comment by aleb** [comment]
Please try with the latest version. http://wiki.pitivi.org/wiki/Install_with_flatpak

**Comment by procod3R** [comment]
.deb file ?

**Comment by procod3R** [comment]
![screenshot from 2016-10-09 00-45-57](https://cloud.githubusercontent.com/assets/5165343/19216390/c4463eb4-8db9-11e6-853b-e8b8cc579764.png)

**Comment by procod3R** [comment]
LO
![screenshot from 2016-10-09 00-50-36](https://cloud.githubusercontent.com/assets/5165343/19216403/6b4cb5e4-8dba-11e6-9743-beb37bd84bb0.png)

**Comment by aleb** [comment]
Sorry, I meant "latest stable". 
If you want "latest master" please use the latest `pitivi-flatpak`:
```
curl https://git.gnome.org/browse/pitivi/plain/build/flatpak/pitivi-flatpak -Sso pitivi-flatpak && \
   chmod +x pitivi-flatpak && \
  ./pitivi-flatpak --branch=stable --update
```
I'll update the wiki page to mention that to run apps installed with Flatpak from the system menu, you have to re-login. This needs to be done only once after installing Flatpak. Until then you can run in the command line "flatpak run org.pitivi.Pitivi". Thanks!

**Comment by procod3R** [comment]
same , please send me .deb file it's hard to install via flatpak
![screenshot from 2016-10-09 14-33-07](https://cloud.githubusercontent.com/assets/5165343/19220427/56a6de3a-8e2d-11e6-9aa8-c8d87a0a69cb.png)

**Comment by procod3R** [comment]
v0.95 on gnome software ?

**Comment by aleb** [comment]
We do not afford spending time on building deb, rpm, etc. With flatpak you can install Pitivi anywhere. Usability should get better soon, Flatpak is still new. Sorry for the rough experience.

From your last screenshot I see a file or directory cannot be written in your `~/.local/share/flatpak` directory. You can investigate why it fails, check the write-ability of all the directories in that path and if they are owned by you or by root.

**Comment by aleb** [comment]
From the screenshot I see "--branch=stable" and I see I wrote "stable" in the command I gave you last time, which was wrong, please use this:
```
curl https://git.gnome.org/browse/pitivi/plain/build/flatpak/pitivi-flatpak -Sso pitivi-flatpak && \
   chmod +x pitivi-flatpak && \
  ./pitivi-flatpak --branch=master --update
```

**Comment by procod3R** [comment]
![screenshot from 2016-10-09 23-42-20](https://cloud.githubusercontent.com/assets/5165343/19223858/2a90566c-8e7a-11e6-8806-3432557d566a.png) ...........

**Comment by procod3R** [comment]
???

**Comment by aleb** [comment]
Do you have some time to come to our IRC channel? #pitivi on freenode.
We need to investigate why the script is not working.

**Comment by procod3R** [comment]
ok

**Comment by aleb** [comment]
Do you still get an error when adding "Agingtv" to a clip? (when you start Pitivi like "flatpak run org.pitivi.Pitivi")

**Comment by aleb** [comment]
Please reopen if it's still an issue, preferably on https://phabricator.freedesktop.org/project/view/15/ and tag it with `Pitivi`.
