### ISSUE TITLE
GtkHScrollbar 0x21ea8b0 is drawn without a current allocation. This should not happen.

### ISSUE THREAD

**Issue by shakaran** [pitivi/pitivi#145]
Using latest master. Starting pitivi shows several warnings:

	$ pitivi
	Running in sandbox: /myroute/pitivi-dev/pitivi/bin/pitivi
	Missing soft dependency:
	- pycanberra not found on the system
		-> enables sound notifications when rendering is complete

	(pitivi:3): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned

	(pitivi:3): Gtk-WARNING **: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned

	(pitivi:3): Gtk-WARNING **: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned

	(pitivi:3): Gtk-WARNING **: GtkHScrollbar 0x21ea8b0 is drawn without a current allocation. This should not happen.

	(pitivi:3): Gtk-WARNING **: GtkVScrollbar 0x21ea6b0 is drawn without a current allocation. This should not happen.

	(pitivi:3): Gtk-WARNING **: GtkVScrollbar 0x21ea6b0 is drawn without a current allocation. This should not happen.

	(pitivi:3): Gtk-WARNING **: GtkVScrollbar 0x21ea6b0 is drawn without a current allocation. This should not happen.

**Comment by shakaran** [comment]
During the session, other similar warnings in other widgets:

	(pitivi:3): Gtk-WARNING **: PitiviUriVideoSource 0x7fd9a98eaaa0 is drawn without a current allocation. This should not happen.

	(pitivi:3): Gtk-WARNING **: pitivi+timeline+elements+VideoBackground 0x7fd990066730 is drawn without a current allocation. This should not happen.

	(pitivi:3): Gtk-WARNING **: pitivi+timeline+previewers+VideoPreviewer 0x7fd9901f21f0 is drawn without a current allocation. This should not happen.

**Comment by aleb** [comment]
Please subscribe to https://phabricator.freedesktop.org/T7573 to follow the progress.
