### ISSUE TITLE
Test 21/24 failed, missing directory too

### ISSUE THREAD

**Issue by shakaran** [pitivi/pitivi#150]
The test is looking:

    /home/shakaran/Documentos/ProjectsSSD/pitivi-dev/pitivi/mesonbuild/meson-private/meson

But the in /home/shakaran/Documentos/ProjectsSSD/pitivi-dev/pitivi/mesonbuild/meson-private/

There is not "meson" folder.

	(ptv-flatpak) shakaran@otorion:~/Documentos/ProjectsSSD/pitivi-dev/pitivi$ make check
	Running in sandbox: make check
	cd /home/shakaran/Documentos/ProjectsSSD/pitivi-dev/pitivi/mesonbuild && ninja test
	[2/3] Running all tests.
	 1/24 Test application module                 OK       7.23 s
	 2/24 Test check module                       OK       7.17 s
	 3/24 Test clipproperties                     OK       6.24 s
	 4/24 Test common utilities                   OK       7.15 s
	 5/24 Test logging subsystem                  OK       6.22 s
	 6/24 Test the main window                    OK      10.17 s
	 7/24 Test the media library                  OK      16.86 s
	 8/24 Test the misc utilities                 OK       6.16 s
	 9/24 Test the pipeline                       OK       4.18 s
	10/24 Test the preference dialog              OK       3.26 s
	11/24 Test presets                            OK       3.29 s
	12/24 Test the previewer                      OK       7.01 s
	13/24 Test the project                        OK       6.62 s
	14/24 Test the keyboard shortcuts             OK       3.17 s
	15/24 Test system integration                 OK       3.50 s
	16/24 Test graphical timeline elements        OK       9.76 s
	17/24 Test graphical layers                   OK       4.88 s
	18/24 Test the graphical timeline             OK      15.55 s
	19/24 Test undo/redo for the project          OK       8.65 s
	20/24 Test the undo subsystem                 OK       3.78 s
	21/24 Test undo/redo in the timeline          FAIL    11.42 s
	22/24 Test utilities                          OK       3.71 s
	23/24 Test the timeline utilities             OK       4.68 s
	24/24 Test our compound widget                OK       3.34 s
	Full log written to meson-logs/testlog.txt.
	FAILED: test 
	'/usr/bin/python3' '/app/bin/meson.py' '--internal' 'test' '/home/shakaran/Documentos/ProjectsSSD/pitivi-dev/pitivi/mesonbuild/meson-private/meson_test_setup.dat'
	ninja: build stopped: subcommand failed.
	Makefile:8: recipe for target 'check' failed
	make: *** [check] Error 1

**Comment by thiblahute** [comment]
That test works here, where do you see it used `/home/shakaran/Documentos/ProjectsSSD/pitivi-dev/pitivi/mesonbuild/meson-private/meson`?

Alsi please use our official project management tool/bug tracker: https://phabricator.freedesktop.org/tag/pitivi/

Closing, and feel free to reopen in there!

Thanks a lot for reporting :)

**Comment by shakaran** [comment]
@thiblahute Thanks for your reply. I actually see that warning after execute the command:

'/usr/bin/python3' '/app/bin/meson.py' '--internal' 'test' '/home/shakaran/Documentos/ProjectsSSD/pitivi-dev/pitivi/mesonbuild/meson-private/meson_test_setup.dat'

With (ptv-flatpak) enviroment enabled. Phabricator is good, and open source, but a bit confused to me since I know better github and for me is more friendly, but well next time I will report there

**Comment by aleb** [comment]
Could you please clarify how to reproduce?
