### ISSUE TITLE
Consider integrate pycamberra inside of pitivi

### ISSUE THREAD

**Issue by shakaran** [pitivi/pitivi#151]
This [launchpad bug](https://bugs.launchpad.net/ubuntu/+source/pitivi/+bug/1379678) was reported by me a lot time ago.

After almost 2 years it would be a low priority or whilist for ubuntu maintaners. I purpuse that the script would be integrated inside of pitivi, since [according to his repository](https://github.com/psykoyiko/pycanberra/blob/master/pycanberra.py) it doesn't have any update in more than 4 years and get rid the message at startup in pitivi about install pycamberra, which confuse a lot to the new users.

**Comment by thiblahute** [comment]
Closing as I reopened it on our official bug tracker: https://phabricator.freedesktop.org/T7598


We should stop using pycanberra and port to proper introspected libcanberra as explain in https://wiki.archlinux.org/index.php/Libcanberra it should be really straight forward

Thanks for the bug report and please report on phabricator next time! :)

**Comment by shakaran** [comment]
@thiblahute it seems that you forgot to close actually this issue
