### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by werewolfy** [pitivi/pitivi#154]
When running

$ flatpak install --user http://flatpak.pitivi.org/pitivi.flatpakref

after

      Installing: org.gnome.Platform/x86_64/3.24 from gnome
      [####################] 9 delta parts, 84 loose fetched; 196242 KiB transferred in 239 seconds
      Installing: org.gnome.Platform.Locale/x86_64/3.24 from gnome
      [####################] 4 metadata, 1 content objects fetched; 14 KiB transferred in 2 seconds
      Installing: org.pitivi.Pitivi/x86_64/stable from org.pitivi.Pitivi-1-origin

I get the following error:

      [###                 ] Downloading files: 85/882 116,2 kB (58,1 kB/s)              
      error: While pulling app/org.pitivi.Pitivi/x86_64/stable from remote org.pitivi.Pitivi-1-origin: Server 
      returned status 403: Forbidden

Looks like a server settings problem...

Please correct!

**Comment by aleb** [comment]
Works fine here, please retry.

**Comment by werewolfy** [comment]
Of course that was the first thing I tried (even twice!), before submitting the issue...
 

Gesendet: Mittwoch, 25. Oktober 2017 um 00:01 Uhr
Von: "Alex Băluț" <notifications@github.com>
An: pitivi/pitivi <pitivi@noreply.github.com>
Cc: werewolfy <wolfgangh@gmx.com>, Author <author@noreply.github.com>
Betreff: Re: [pitivi/pitivi] Installation error (#154)


Works fine here, please retry.

**Comment by aleb** [comment]
Are you still getting the 403 Forbidden error?
Does it work if you install the master version? `flatpak install --user http://flatpak.pitivi.org/pitivi-master.flatpakref`

**Comment by werewolfy** [comment]
Yes, I still get the error.

When I try the master version, I get the following error:

 

"error: While pulling app/org.pitivi.Pitivi/x86_64/master from remote org.pitivi.Pitivi-3-origin: Server returned status 403: Forbidden"

 

 

Gesendet: Mittwoch, 25. Oktober 2017 um 00:39 Uhr
Von: "Alex Băluț" <notifications@github.com>
An: pitivi/pitivi <pitivi@noreply.github.com>
Cc: werewolfy <wolfgangh@gmx.com>, Author <author@noreply.github.com>
Betreff: Re: [pitivi/pitivi] Installation error (#154)


Are you still getting the 403 Forbidden error?
Does it work if you install the master version? flatpak install --user http://flatpak.pitivi.org/pitivi-master.flatpakref

**Comment by aleb** [comment]
It works fine here. Please ask the Flatpak team about how to find out which URL returns 403.

```
$ flatpak install --user http://flatpak.pitivi.org/pitivi.flatpakref
This application depends on runtimes from:
  https://sdk.gnome.org/repo/
Configure this as new remote 'gnome' [y/n]: y
Installing: org.pitivi.Pitivi/x86_64/stable
Required runtime for org.pitivi.Pitivi/x86_64/stable (org.gnome.Platform/x86_64/3.24) is not installed, searching...
Found in remote gnome, do you want to install it? [y/n]: y
Installing: org.gnome.Platform/x86_64/3.24 from gnome
[####################] 9 delta parts, 71 loose fetched; 191070 KiB transferred in 20 seconds
Installing: org.freedesktop.Platform.GL.nvidia-384-69/x86_64/1.4 from gnome
[####################] Downloading: 46.1 MB/46.1 MB (2.4 MB/s)                 
Installing: org.gnome.Platform.Locale/x86_64/3.24 from gnome
[####################] 4 metadata, 1 content objects fetched; 14 KiB transferred in 2 seconds
Installing: org.pitivi.Pitivi/x86_64/stable from org.pitivi.Pitivi-origin
[####################] 659 metadata, 4473 content objects fetched; 83307 KiB transferred in 95 seconds

$ echo $?
0
```
