### ISSUE TITLE
Cannot run pitivi

### ISSUE THREAD

**Issue by andrey-kosinov** [pitivi/pitivi#164]
When I try to run pitivi I see this error message:

```
$ pitivi
Gdk-Message: 23:07:32.157: pitivi: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.0.

```
What could it be ?

**Comment by aleb** [comment]
How did you install it?

**Comment by andrey-kosinov** [comment]
Hi!
I installed in from community repo in Manjaro Linux.
I have version Pitivi (pitivi)  0.999-3

**Comment by aleb** [comment]
I understand the error is about a failed interaction with the X server. Maybe try restarting the computer. If it persists, you could ask the Manjaro team responsible for this package. You could also ask on IRC GimpNode#gtk. 

We don't interact directly with X, so I'll close this. Please report future issues to https://gitlab.gnome.org/GNOME/pitivi

Alternatively you can install Pitivi using flatpak: https://flathub.org/apps/details/org.pitivi.Pitivi

**Comment by andrey-kosinov** [comment]
ok. thank you
