### ISSUE TITLE
Need to implement a color picker

### ISSUE THREAD

**Issue by thiblahute** [pitivi/pitivi#30]
Need to implement a color picker that works and is future-proof even with Wayland. In the meantime, we should hide the color picker widget.

Maybe by grabbing to sample the average color by converting the UI coordinates to the resolution coordinates and asking the gstreamer pipeline to give us a snapshot at that moment in time and running our analysis on it

 It also needs to automatically and temporarily deactivate the chromakey effect while color picking. See kdenlive for an example of a nice UI behavior in that regard.

**Comment by aleb** [comment]
https://phabricator.freedesktop.org/T3426
