### ISSUE TITLE
When prompting for a missing file on project load, don’t just show the duration, also show the filesize (that one might require formatter changes)

### ISSUE THREAD

**Issue by thiblahute** [pitivi/pitivi#36]
@nekohayo Isn't that fixed?!

**Comment by aleb** [comment]
The filesize is not saved in the xges file. For example:

`      <asset id='file:///home/aleb/Downloads/aerial-shot-of-three-motorcycles-on-monument-valley-highway_bk3ct62lb__Dx.mp4' extractable-type-name='GESUriClip' properties='properties, supported-formats=(int)4, duration=(guint64)9008333333;' metadatas='metadatas, video-codec=(string)&quot;H.264\ /\ AVC&quot;, maximum-bitrate=(uint)17416176, bitrate=(uint)11676240, datetime=(datetime)2014-10-17T06:45:40Z, container-format=(string)&quot;ISO\ MP4/M4A&quot;;' />
`
