### ISSUE TITLE
gnltests: gstdump GST_DEBUG=2 GST_CHECKS=test_complex_operations_bis make gnl/seek.check

### ISSUE THREAD

**Issue by thiblahute** [pitivi/pitivi#45]
Error:

    gnl/common.h:123:F:general:test_complex_operations_bis:0: Received unexpected segment

Observed:

- We get weird BUFFER.duration from videomixer, we should take into accound segment.start and we currently do not... it breaks things and results in basesink dropping buffers

\

    in basesink.c
    GST_DEBUG_OBJECT (basesink, "dropping buffer, out of clipping segment");

- After hacking a solution for the first point, we notice that we get an unexpected segment because the videomixer received EOS on its sinkpads, and gnl receives EOS, and updates the pipeline, which implies resending new segments.

I thought we could accept unexpected new segment in the tests, but I am unsure about that. I have a patch for that here: http://cgit.collabora.com/git/user/tsaunier/gnonlin/commit/?h=fixes&id=7d040821dfa4475d48ed5e7ad62fd54038f0a63c

**Comment by aleb** [comment]
Obsolete (gnonlin)
