### ISSUE TITLE
Show the resulting video in the viewer while rendering

### ISSUE THREAD

**Issue by nekohayo** [pitivi/pitivi#58]
Not a huge huge regression, but Pitivi 0.15 showed the visual state of the pipeline while rendering, which is probably computationally inexpensive (if at all) and is a very nice indication, especially when it comes to figuring out where exactly a render hangs (if, sadly, it happens).

Would be cool to re-enable that for the release, though obviously not a blocker.

**Comment by aleb** [comment]
Ignoring because we need to get to 1.0 before this.
