### ISSUE TITLE
Super slow waveform generation for a particular webm clip

### ISSUE THREAD

**Issue by nekohayo** [pitivi/pitivi#81]
Import http://jeff.ecchi.ca/public/Humans%20Yelling%20Like%20Goats%20Yelling%20Like%20Humans.webm into a blank timeline.

In my case, after 5-10 minutes, long after all the video thumbnail tiles have been generated, pitivi is still using the cpu (eating roughly 1 out of 4 cores) and no waveform ever gets displayed, even if I zoom in and out.

**Comment by aleb** [comment]
Seems to work fine now, tried with sintel-1024-stereo.mp4
